package org.seleznyov.iyu.kfin.ledger.infrastructure.memory.arena;

import java.lang.foreign.ValueLayout;

public interface PartitionUpdateAmountOffsetConstants {
    int CPU_CACHE_LINE_SIZE = 64;

    int PARTITION_UPDATE_ACCOUNT_ID_MSB_OFFSET = 0;
    ValueLayout PARTITION_UPDATE_ACCOUNT_ID_SB_TYPE = ValueLayout.JAVA_LONG;
    int PARTITION_UPDATE_ACCOUNT_ID_LSB_OFFSET = (int) (PARTITION_UPDATE_ACCOUNT_ID_MSB_OFFSET + PARTITION_UPDATE_ACCOUNT_ID_SB_TYPE.byteSize());

    int PARTITION_UPDATE_AMOUNT_OFFSET = (int) (PARTITION_UPDATE_ACCOUNT_ID_LSB_OFFSET + PARTITION_UPDATE_ACCOUNT_ID_SB_TYPE.byteSize());
    ValueLayout PARTITION_UPDATE_AMOUNT_TYPE = ValueLayout.JAVA_LONG;

    int PARTITION_UPDATE_RAW_SIZE = (int) (PARTITION_UPDATE_AMOUNT_OFFSET + PARTITION_UPDATE_AMOUNT_TYPE.byteSize());

    int PARTITION_UPDATE_SIZE = (PARTITION_UPDATE_RAW_SIZE + CPU_CACHE_LINE_SIZE - 1) & -CPU_CACHE_LINE_SIZE;
}
