package org.seleznyov.iyu.kfin.ledger.infrastructure.memory.arena;

import java.lang.foreign.ValueLayout;

public interface TransferRequestOffsetConstants {
    int CPU_CACHE_LINE_SIZE = 64;

    int TRANSFER_AMOUNT_OFFSET = 0;
    ValueLayout.OfLong TRANSFER_AMOUNT_TYPE = ValueLayout.JAVA_LONG;

    int TRANSFER_DEBIT_ACCOUNT_ID_MSB_OFFSET = (int) (TRANSFER_AMOUNT_OFFSET + TRANSFER_AMOUNT_TYPE.byteSize());
    ValueLayout.OfLong TRANSFER_ACCOUNT_ID_SB_TYPE = ValueLayout.JAVA_LONG_UNALIGNED;
    int TRANSFER_DEBIT_ACCOUNT_ID_LSB_OFFSET = (int) (TRANSFER_DEBIT_ACCOUNT_ID_MSB_OFFSET + TRANSFER_ACCOUNT_ID_SB_TYPE.byteSize());

    int TRANSFER_CREDIT_ACCOUNT_ID_MSB_OFFSET = (int) (TRANSFER_DEBIT_ACCOUNT_ID_LSB_OFFSET + TRANSFER_ACCOUNT_ID_SB_TYPE.byteSize());
    int TRANSFER_CREDIT_ACCOUNT_ID_LSB_OFFSET = (int) (TRANSFER_CREDIT_ACCOUNT_ID_MSB_OFFSET + TRANSFER_ACCOUNT_ID_SB_TYPE.byteSize());

    int TRANSFER_CREATED_AT_OFFSET = (int) (TRANSFER_CREDIT_ACCOUNT_ID_LSB_OFFSET + TRANSFER_ACCOUNT_ID_SB_TYPE.byteSize());
    ValueLayout.OfLong TRANSFER_CREATED_AT_TYPE = ValueLayout.JAVA_LONG;

    int TRANSFER_ID_MSB_OFFSET = (int) (TRANSFER_CREATED_AT_OFFSET + TRANSFER_CREATED_AT_TYPE.byteSize());
    ValueLayout.OfLong TRANSFER_ID_TYPE = ValueLayout.JAVA_LONG;
    int TRANSFER_ID_LSB_OFFSET = (int) (TRANSFER_ID_MSB_OFFSET + TRANSFER_ID_TYPE.byteSize());

    int TRANSFER_IDEMPOTENCY_KEY_MSB_OFFSET = (int) (TRANSFER_ID_LSB_OFFSET + TRANSFER_ID_TYPE.byteSize());
    ValueLayout.OfLong TRANSFER_IDEMPOTENCY_KEY_TYPE = ValueLayout.JAVA_LONG_UNALIGNED;
    int TRANSFER_IDEMPOTENCY_KEY_LSB_OFFSET = (int) (TRANSFER_IDEMPOTENCY_KEY_MSB_OFFSET + TRANSFER_IDEMPOTENCY_KEY_TYPE.byteSize());

    int TRANSFER_CURRENCY_CODE_OFFSET = (int) (TRANSFER_IDEMPOTENCY_KEY_LSB_OFFSET + TRANSFER_IDEMPOTENCY_KEY_TYPE.byteSize());
    ValueLayout.OfLong TRANSFER_CURRENCY_CODE_TYPE = ValueLayout.JAVA_LONG_UNALIGNED;

    int TRANSFER_RAW_SIZE = (int) (TRANSFER_CURRENCY_CODE_OFFSET + TRANSFER_CURRENCY_CODE_TYPE.byteSize());

    int TRANSFER_STAMP_SIZE = (TRANSFER_RAW_SIZE + CPU_CACHE_LINE_SIZE - 1) & -CPU_CACHE_LINE_SIZE;
}
