services:
  ledger_db:
    #build: ./
    image: ledger_db:latest
    container_name: ledger_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/wrks/bin/postgresql/data/k-stories:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    shm_size: 1gb                    # Увеличиваем shared memory до 2GB
    deploy:
      resources:
        limits:
          memory: 2g               # Лимит памяти 2GB
          cpus: '2'                # 2 CPU ядра
        reservations:
          memory: 512m             # Минимум 512MB
          cpus: '1'
    command: >
      postgres
      -c shared_buffers=256MB
      -c maintenance_work_mem=512MB
      -c effective_cache_size=1GB
      -c random_page_cost=1.1
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c max_connections=100
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c log_statement=all
      -c log_duration=on
      -c log_min_duration_statement=1000
#volumes:
#  data:
#    driver: local

networks:
  pgnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local
    # Оптимизация volume для macOS
    driver_opts:
      type: none
      o: bind
      device: ./postgres_data