package org.seleznyov.iyu.kfin.ledgerservice.core.constants;

import java.lang.foreign.ValueLayout;

import static org.seleznyov.iyu.kfin.ledgerservice.core.constants.CommonConstants.CPU_CACHE_LINE_SIZE;
import static org.seleznyov.iyu.kfin.ledgerservice.core.constants.CommonConstants.LENGTH_TYPE;

public interface SnapshotOffsetConstants {
    int FIELD_COUNT_OFFSET = 0;
    ValueLayout FIELD_COUNT_TYPE = ValueLayout.JAVA_SHORT;

    int SNAPSHOT_BALANCE_LENGTH_OFFSET = (int) (FIELD_COUNT_OFFSET + FIELD_COUNT_TYPE.byteSize());

    int SNAPSHOT_BALANCE_OFFSET = (int) (SNAPSHOT_BALANCE_LENGTH_OFFSET + LENGTH_TYPE.byteSize());
    ValueLayout.OfLong SNAPSHOT_BALANCE_TYPE = ValueLayout.JAVA_LONG;

    int SNAPSHOT_ID_LENGTH_OFFSET = (int) (SNAPSHOT_BALANCE_OFFSET + SNAPSHOT_BALANCE_TYPE.byteSize());

    int SNAPSHOT_ID_MSB_OFFSET = (int) (SNAPSHOT_ID_LENGTH_OFFSET + LENGTH_TYPE.byteSize());
    ValueLayout.OfLong SNAPSHOT_ID_SB_TYPE = ValueLayout.JAVA_LONG;
    int SNAPSHOT_ID_LSB_OFFSET = (int) (SNAPSHOT_ID_MSB_OFFSET + SNAPSHOT_ID_SB_TYPE.byteSize());

    int SNAPSHOT_CREATED_AT_LENGTH_OFFSET = (int) (SNAPSHOT_ID_LSB_OFFSET + SNAPSHOT_ID_SB_TYPE.byteSize());
    int SNAPSHOT_CREATED_AT_OFFSET = (int) (SNAPSHOT_CREATED_AT_LENGTH_OFFSET + LENGTH_TYPE.byteSize());
    ValueLayout.OfLong SNAPSHOT_CREATED_AT_TYPE = ValueLayout.JAVA_LONG;

    int SNAPSHOT_OPERATION_DAY_LENGTH_OFFSET = (int) (SNAPSHOT_CREATED_AT_OFFSET + SNAPSHOT_CREATED_AT_TYPE.byteSize());
    int SNAPSHOT_OPERATION_DAY_OFFSET = (int) (SNAPSHOT_OPERATION_DAY_LENGTH_OFFSET + LENGTH_TYPE.byteSize());
    ValueLayout.OfLong SNAPSHOT_OPERATION_DAY_TYPE = ValueLayout.JAVA_LONG;

    int SNAPSHOT_ACCOUNT_ID_LENGTH_OFFSET = (int) (SNAPSHOT_OPERATION_DAY_OFFSET + SNAPSHOT_OPERATION_DAY_TYPE.byteSize());
    int SNAPSHOT_ACCOUNT_ID_MSB_OFFSET = (int) (SNAPSHOT_ACCOUNT_ID_LENGTH_OFFSET + LENGTH_TYPE.byteSize());
    ValueLayout.OfLong SNAPSHOT_ACCOUNT_ID_TYPE = ValueLayout.JAVA_LONG;
    int SNAPSHOT_ACCOUNT_ID_LSB_OFFSET = (int) (SNAPSHOT_ACCOUNT_ID_MSB_OFFSET + SNAPSHOT_ACCOUNT_ID_TYPE.byteSize());

    int SNAPSHOT_CURRENCY_CODE_LENGTH_OFFSET = (int) (SNAPSHOT_ACCOUNT_ID_LSB_OFFSET + SNAPSHOT_ACCOUNT_ID_TYPE.byteSize());
    int SNAPSHOT_CURRENCY_CODE_OFFSET = (int) (SNAPSHOT_CURRENCY_CODE_LENGTH_OFFSET + LENGTH_TYPE.byteSize());
    ValueLayout.OfLong SNAPSHOT_CURRENCY_CODE_TYPE = ValueLayout.JAVA_LONG;

    int SNAPSHOT_ORDINAL_LENGTH_OFFSET = (int) (SNAPSHOT_CURRENCY_CODE_OFFSET + SNAPSHOT_CURRENCY_CODE_TYPE.byteSize());
    int SNAPSHOT_ORDINAL_OFFSET = (int) (SNAPSHOT_ORDINAL_LENGTH_OFFSET + LENGTH_TYPE.byteSize());
    ValueLayout.OfLong SNAPSHOT_ORDINAL_TYPE = ValueLayout.JAVA_LONG;

    int SNAPSHOT_ENTRY_RECORD_ORDINAL_LENGTH_OFFSET = (int) (SNAPSHOT_ORDINAL_OFFSET + SNAPSHOT_ORDINAL_TYPE.byteSize());
    int SNAPSHOT_ENTRY_RECORD_ORDINAL_OFFSET = (int) (SNAPSHOT_ENTRY_RECORD_ORDINAL_LENGTH_OFFSET + LENGTH_TYPE.byteSize());
    ValueLayout.OfLong SNAPSHOT_ENTRY_RECORD_ORDINAL_TYPE = ValueLayout.JAVA_LONG;

    int POSTGRES_SNAPSHOT_RAW_SIZE = (int) (SNAPSHOT_ENTRY_RECORD_ORDINAL_OFFSET + SNAPSHOT_ENTRY_RECORD_ORDINAL_TYPE.byteSize());

    int POSTGRES_SNAPSHOT_SIZE = (POSTGRES_SNAPSHOT_RAW_SIZE + CPU_CACHE_LINE_SIZE - 1) & -CPU_CACHE_LINE_SIZE;
}
